import string
REGEX = 'regex'


OR = 'OR'
AND = 'AND'
SYMBOL = 'SYMBOL'

ENTER_GROUP = 'ENTER_GROUP'
EXIT_GROUP = 'EXIT_GROUP'
SPACE = 'SPACE'

ENTER_GROUP_VALUE = '('
EXIT_GROUP_VALUE = ')'
SPACE_VALUE = ' '
SPACE_VALUES = [i for i in string.whitespace]


AND_TERMINATORS = [ENTER_GROUP_VALUE, EXIT_GROUP_VALUE] + SPACE_VALUES
OR_TERMINATORS = [ENTER_GROUP_VALUE, EXIT_GROUP_VALUE] + SPACE_VALUES
SYM_TERMINATORS = [ENTER_GROUP_VALUE, EXIT_GROUP_VALUE] + SPACE_VALUES

SYMBOL_NEXT = [AND, OR, EXIT_GROUP]
SPACE_NEXT = [SYMBOL, AND, OR, SPACE, ENTER_GROUP, EXIT_GROUP]
OR_NEXT = [ENTER_GROUP, EXIT_GROUP, SYMBOL]
AND_NEXT = [ENTER_GROUP, EXIT_GROUP, SYMBOL]
ENTER_GROUP_NEXT = [SYMBOL, ENTER_GROUP, EXIT_GROUP]
EXIT_GROUP_NEXT = [ENTER_GROUP, EXIT_GROUP, AND, OR]


PREDICATE = 'PREDICATE'
ACTION = 'ACTION'